/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc_message_storage.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

int
_rpc_register_1 (char * *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_register_1_svc(*argp, result, rqstp));
}

int
_rpc_unregister_1 (char * *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_unregister_1_svc(*argp, result, rqstp));
}

int
_rpc_user_exists_1 (char * *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_user_exists_1_svc(*argp, result, rqstp));
}

int
_rpc_retrieve_last_identifier_1 (char * *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_retrieve_last_identifier_1_svc(*argp, result, rqstp));
}

int
_rpc_retrieve_message_number_1 (char * *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_retrieve_message_number_1_svc(*argp, result, rqstp));
}

int
_rpc_retrieve_user_message_1 (rpc_retrieve_user_message_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (rpc_retrieve_user_message_1_svc(argp->username, argp->message_identifier, result, rqstp));
}

int
_store_user_message_1 (store_user_message_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (store_user_message_1_svc(argp->username, argp->username_sender, argp->message, result, rqstp));
}

int
_delete_user_message_1 (delete_user_message_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (delete_user_message_1_svc(argp->username, argp->message_identifier, result, rqstp));
}

static void
message_storage_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		char *rpc_register_1_arg;
		char *rpc_unregister_1_arg;
		char *rpc_user_exists_1_arg;
		char *rpc_retrieve_last_identifier_1_arg;
		char *rpc_retrieve_message_number_1_arg;
		rpc_retrieve_user_message_1_argument rpc_retrieve_user_message_1_arg;
		store_user_message_1_argument store_user_message_1_arg;
		delete_user_message_1_argument delete_user_message_1_arg;
	} argument;
	union {
		int rpc_register_1_res;
		int rpc_unregister_1_res;
		int rpc_user_exists_1_res;
		int rpc_retrieve_last_identifier_1_res;
		int rpc_retrieve_message_number_1_res;
		user_message rpc_retrieve_user_message_1_res;
		int store_user_message_1_res;
		int delete_user_message_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case rpc_register:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_register_1;
		break;

	case rpc_unregister:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_unregister_1;
		break;

	case rpc_user_exists:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_user_exists_1;
		break;

	case rpc_retrieve_last_identifier:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_retrieve_last_identifier_1;
		break;

	case rpc_retrieve_message_number:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_retrieve_message_number_1;
		break;

	case rpc_retrieve_user_message:
		_xdr_argument = (xdrproc_t) xdr_rpc_retrieve_user_message_1_argument;
		_xdr_result = (xdrproc_t) xdr_user_message;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpc_retrieve_user_message_1;
		break;

	case store_user_message:
		_xdr_argument = (xdrproc_t) xdr_store_user_message_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_store_user_message_1;
		break;

	case delete_user_message:
		_xdr_argument = (xdrproc_t) xdr_delete_user_message_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_delete_user_message_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!message_storage_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (MESSAGE_STORAGE, MESSAGE_STORAGEVER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, MESSAGE_STORAGE, MESSAGE_STORAGEVER, message_storage_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (MESSAGE_STORAGE, MESSAGE_STORAGEVER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, MESSAGE_STORAGE, MESSAGE_STORAGEVER, message_storage_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (MESSAGE_STORAGE, MESSAGE_STORAGEVER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
