
package wsclient;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CapitalizationServiceService", targetNamespace = "http://capitalizationwebservice/", wsdlLocation = "META-INF/wsdl/CapitalizationService.wsdl")
public class CapitalizationServiceService
    extends Service
{

    private final static URL CAPITALIZATIONSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException CAPITALIZATIONSERVICESERVICE_EXCEPTION;
    private final static QName CAPITALIZATIONSERVICESERVICE_QNAME = new QName("http://capitalizationwebservice/", "CapitalizationServiceService");

    static {
        CAPITALIZATIONSERVICESERVICE_WSDL_LOCATION = wsclient.CapitalizationServiceService.class.getClassLoader().getResource("META-INF/wsdl/CapitalizationService.wsdl");
        WebServiceException e = null;
        if (CAPITALIZATIONSERVICESERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/CapitalizationService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        CAPITALIZATIONSERVICESERVICE_EXCEPTION = e;
    }

    public CapitalizationServiceService() {
        super(__getWsdlLocation(), CAPITALIZATIONSERVICESERVICE_QNAME);
    }

    public CapitalizationServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CAPITALIZATIONSERVICESERVICE_QNAME, features);
    }

    public CapitalizationServiceService(URL wsdlLocation) {
        super(wsdlLocation, CAPITALIZATIONSERVICESERVICE_QNAME);
    }

    public CapitalizationServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CAPITALIZATIONSERVICESERVICE_QNAME, features);
    }

    public CapitalizationServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CapitalizationServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CapitalizationService
     */
    @WebEndpoint(name = "CapitalizationServicePort")
    public CapitalizationService getCapitalizationServicePort() {
        return super.getPort(new QName("http://capitalizationwebservice/", "CapitalizationServicePort"), CapitalizationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CapitalizationService
     */
    @WebEndpoint(name = "CapitalizationServicePort")
    public CapitalizationService getCapitalizationServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://capitalizationwebservice/", "CapitalizationServicePort"), CapitalizationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CAPITALIZATIONSERVICESERVICE_EXCEPTION!= null) {
            throw CAPITALIZATIONSERVICESERVICE_EXCEPTION;
        }
        return CAPITALIZATIONSERVICESERVICE_WSDL_LOCATION;
    }

}
