/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "rpc_message_storage.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
rpc_register_1(char *username, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_register,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &username,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_unregister_1(char *username, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_unregister,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &username,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_user_exists_1(char *username, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_user_exists,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &username,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_retrieve_last_identifier_1(char *username, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_retrieve_last_identifier,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &username,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_retrieve_message_number_1(char *username, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_retrieve_message_number,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &username,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_retrieve_user_message_1(char *username, int message_identifier, user_message *clnt_res,  CLIENT *clnt)
{
	rpc_retrieve_user_message_1_argument arg;
	arg.username = username;
	arg.message_identifier = message_identifier;
	return (clnt_call (clnt, rpc_retrieve_user_message, (xdrproc_t) xdr_rpc_retrieve_user_message_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_user_message, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
store_user_message_1(char *username, char *username_sender, char *message, int *clnt_res,  CLIENT *clnt)
{
	store_user_message_1_argument arg;
	arg.username = username;
	arg.username_sender = username_sender;
	arg.message = message;
	return (clnt_call (clnt, store_user_message, (xdrproc_t) xdr_store_user_message_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
delete_user_message_1(char *username, int message_identifier, int *clnt_res,  CLIENT *clnt)
{
	delete_user_message_1_argument arg;
	arg.username = username;
	arg.message_identifier = message_identifier;
	return (clnt_call (clnt, delete_user_message, (xdrproc_t) xdr_delete_user_message_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
